/// <reference types="vite/client" />

VITE_SUPABASE_URL=https://plgupdwglfopxjoxwyys.supabase.co
VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsZ3VwZHdnbGZvcHhqb3h3eXlzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5MTY4MTMsImV4cCI6MjA4ODQ5MjgxM30.L0dVoOa6SAhbTRkLg_wov71TFWZM9biPG63NMaXAMiY
